# .travis.yml
language: python
sudo: true

env:
  - LUA="lua=5.1" LUAC="luac5.1"

addons:
  apt:
    packages:
      - liblua5.1-bitop0

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install mockagne 1.0
  - luarocks install luaunit
  - luarocks install luabitop
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - luacheck --std max+busted GS-Core/startup.lua --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences
  - luacheck --no-unused --allow-defined --std max+busted GS-Core/errorhandler.lua --globals seterrorhandler currentclassDisplayName
  - luacheck --std max+busted GS-Core/Core.lua --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences
  - luacheck --std max+busted GS-SequenceEditor/editor-core.lua --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences
  - luacheck --std max+busted GS-DraikMacros/Macros/*.lua --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences
  - pwd
  - busted --verbose --coverage

after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install

notifications:
  email:
    on_failure: always
    on_success: change

cache:
  apt: true
  directories:
    - $HOME/.luarocks
