# This is a basic workflow to help you get started with Actions

name: CI_BETA

# Controls when the action will run. 
on:
  push:
    branches:
      - '!master'
      - 'Midnight'
  pull_request:
    branches:
      - 'Midnight'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    # Runs a single command using the runners shell
    - name: Install and Run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: -q

    # do Busted checkes
    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Build Luarocks
      run: |
        luarocks install mockagne 1.0
        luarocks install luaunit
        # luarocks install luabitop
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-coveralls
        luarocks install luadoc
       # luarocks install rockspecs/luacov-coveralls-scm-0.rockspec
        
    - name: Run Busted UnitTests
      run: |
        busted -o utfTerminal --verbose --coverage

    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Install Dependencies
      run: npm ci
    - name: Update GSE/API/Patreon.lua
      run: npm run-script run
      env: 
          NODE_PATREON_TOKEN: ${{secrets.PATREON_CAT }}
          
    # Runs a set of commands using the runners shell
    - name: Create Package
      uses: BigWigsMods/packager@master
      if: ${{ github.event_name != 'pull_request' }}
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish Patreon
      run: npm run-script pat
      env: 
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK }}